### ISSUE TITLE
@cypress/skip-test can't be imported

### ISSUE THREAD

**Issue by mellis481** [cypress-io/cypress-skip-test#103]
The [docs](https://github.com/cypress-io/cypress-skip-test#imports) describe being able to import `skipOn` and `onlyOn` like this:

```
import { onlyOn, skipOn } from '@cypress/skip-test'

it('runs only on Mac', () => {
  // using the exported function instead of
  // the custom command cy.onlyOn(...)
  onlyOn('mac')
})

it('skips on Mac', () => {
  skipOn('darwin')
})
```

This doesn't work (at least in Typescript) because _node_modules/@cypress/skip-test/index.d.ts_ is not a module; it's just the Cypress overrides.

**Comment by annaet** [comment]
I fixed this by creating a file called modules.d.ts and declaring the module in there:

declare module '@cypress/skip-test';
Then you can just reference that in any file using:

/// <reference path='../../support/modules.d.ts' />
